version: 2
jobs:
  build-amd64:
    docker:
      - image: 2tefan/cimg-base-buildx:stable-18.04-0.4.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run: docker run  --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
      - run: docker context create testContext
      - run: docker buildx create --use --platform linux/amd64 testContext
      - run: |
          docker buildx build \
            --cache-to=type=local,dest=/home/circleci/docker-cache/linux/amd64 \
            --progress=plain \
            --platform linux/amd64 \
            --tag 2tefan/multiarch-test:buildx \
            .
      - persist_to_workspace:
          root: /home/circleci/docker-cache
          paths:
            - linux/amd64/*

  build-arm64/v8:
    docker:
      - image: 2tefan/cimg-base-buildx:stable-18.04-0.4.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run: docker run  --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
      - run: docker context create testContext
      - run: docker buildx create --use --platform linux/arm64/v8 testContext
      - run: |
          docker buildx build \
            --cache-to=type=local,dest=/home/circleci/docker-cache/linux/arm64/v8 \
            --progress=plain \
            --platform linux/arm64/v8 \
            --tag 2tefan/multiarch-test:buildx \
            .
      - persist_to_workspace:
          root: /home/circleci/docker-cache
          paths:
            - linux/arm64/v8/*

  build-386:
    docker:
      - image: 2tefan/cimg-base-buildx:stable-18.04-0.4.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run: docker run  --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
      - run: docker context create testContext
      - run: docker buildx create --use --platform linux/386 testContext
      - run: |
          docker buildx build \
            --cache-to=type=local,dest=/home/circleci/docker-cache/linux/386 \
            --progress=plain \
            --platform linux/386 \
            --tag 2tefan/multiarch-test:buildx \
            .
      - persist_to_workspace:
          root: /home/circleci/docker-cache
          paths:
            - index.json
            - blobs/*
            - ingest/*

  build-arm/v6:
    docker:
      - image: 2tefan/cimg-base-buildx:stable-18.04-0.4.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run: docker run  --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
      - run: docker context create testContext
      - run: docker buildx create --use --platform linux/arm/v6 testContext
      - run: |
          docker buildx build \
            --cache-to=type=local,dest=/home/circleci/docker-cache/linux/arm/v6 \
            --progress=plain \
            --platform linux/arm/v6 \
            --tag 2tefan/multiarch-test:buildx \
            .
      - persist_to_workspace:
          root: /home/circleci/docker-cache
          paths:
            - index.json
            - blobs/*
            - ingest/*

  build-arm/v7:
    docker:
      - image: 2tefan/cimg-base-buildx:stable-18.04-0.4.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run: docker run  --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
      - run: docker context create testContext
      - run: docker buildx create --use --platform linux/arm/v7 testContext
      - run: |
          docker buildx build \
            --cache-to=type=local,dest=/home/circleci/docker-cache/linux/arm/v7 \
            --progress=plain \
            --platform linux/arm/v7 \
            --tag 2tefan/multiarch-test:buildx \
            .
      - persist_to_workspace:
          root: /home/circleci/docker-cache
          paths:
            - index.json
            - blobs/*
            - ingest/*

  build-ppc64le:
    docker:
      - image: 2tefan/cimg-base-buildx:stable-18.04-0.4.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run: docker run  --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
      - run: docker context create testContext
      - run: docker buildx create --use --platform linux/ppc64le testContext
      - run: |
          docker buildx build \
            --cache-to=type=local,dest=/home/circleci/docker-cache/linux/ppc64le \
            --progress=plain \
            --platform linux/ppc64le \
            --tag 2tefan/multiarch-test:buildx \
            .
      - persist_to_workspace:
          root: /home/circleci/docker-cache
          paths:
            - index.json
            - blobs/*
            - ingest/*

  build-s390x:
    docker:
      - image: 2tefan/cimg-base-buildx:stable-18.04-0.4.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run: docker run  --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
      - run: docker context create testContext
      - run: docker buildx create --use --platform linux/s390x testContext
      - run: |
          docker buildx build \
            --cache-to=type=local,dest=/home/circleci/docker-cache/linux/s390x \
            --progress=plain \
            --platform linux/s390x \
            --tag 2tefan/multiarch-test:buildx \
            .
      - persist_to_workspace:
          root: /home/circleci/docker-cache
          paths:
            - index.json
            - blobs/*
            - ingest/*

  push:
    docker:
      - image: 2tefan/cimg-base-buildx:stable-18.04-0.4.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - attach_workspace:
          at: /home/circleci/docker-cache
      - run: docker run  --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
      - run: docker context create testContext
      - run: docker buildx create --use --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x testContext
      - run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - run: |
          docker buildx build \
            --cache-from=type=local,src=/home/circleci/docker-cache/linux/386 \
            --cache-from=type=local,src=/home/circleci/docker-cache/linux/amd64 \
            --cache-from=type=local,src=/home/circleci/docker-cache/linux/arm/v6 \
            --cache-from=type=local,src=/home/circleci/docker-cache/linux/arm/v7 \
            --cache-from=type=local,src=/home/circleci/docker-cache/linux/arm64/v8 \
            --cache-from=type=local,src=/home/circleci/docker-cache/linux/ppc64le \
            --cache-from=type=local,src=/home/circleci/docker-cache/linux/s390x \
            --progress=plain \
            --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x \
            --tag 2tefan/multiarch-test:buildx \
            --push .

workflows:
 version: 2

 Test_Workflow:
   jobs:
     - build-amd64
     - build-arm64/v8
    #  - build-386
    #  - build-arm/v6
    #  - build-arm/v7
    #  - build-ppc64le
    #  - build-s390x
     
     - push:
          requires:
            - build-amd64
            - build-arm64/v8
            # - build-386
            # - build-arm/v6
            # - build-arm/v7
            # - build-ppc64le
            # - build-s390x
