version: 2
jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run: |
          apk add git docker
      - run: |
          export DOCKER_BUILDKIT=1
      - run: |
          docker build --platform=local -o . git://github.com/docker/buildx
      - run: |
          mkdir -p ~/.docker/cli-plugins
      - run: |
          mv buildx ~/.docker/cli-plugins/docker-buildx
      - run: |
          docker context create testContext
      - run: |
          docker buildx create --use testContext
      - run: |
          docker buildx build \
            --platform linux/arm64/v8,linux/amd64 \
            --tag 2tefan/multiarch-test:test .

workflows:
 version: 2
 Test_Workflow:
   jobs:
     - build
