version: 2
jobs:
  build:
    docker:
      - image: jdrouet/docker-with-buildx:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run: |
          docker context create testContext
      - run: |
          docker buildx create --use testContext
      - run: |
          docker buildx build \
            --platform linux/arm/v7,linux/arm64/v8,linux/amd64 \
            --tag 2tefan/multiarch-test:test .

workflows:
 version: 2
 Test_Workflow:
   jobs:
     - build
