version: 2
jobs:
  setup:
    docker:
      - image: 2tefan/cimg-base-buildx:stable-18.04-0.4.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run: docker run  --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
      - run: docker context create testContext
      - run: docker buildx create --use --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x testContext
      - run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - run: |
          docker buildx build \
            --progress=plain \
            --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x \
            --tag 2tefan/multiarch-test:buildx \
            --push .

  build:
    docker:
      - image: 2tefan/cimg-base-buildx:stable-18.04-0.4.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run: |
          echo "Test"

workflows:
 version: 2

 Test_Workflow:
   jobs:
     - setup
     - build:
          requires:
            - setup
