version: 2
jobs:
build:
  docker:
    - image: 2tefan/multiarch-test:test
  steps:
    - checkout
    - setup_remote_docker:
        version: 18.09.3
    - run: |
        docker buildx build \
          --platform linux/arm/v7,linux/arm64/v8,linux/amd64 \
          --tag your-username/multiarch-example:buildx-latest .
