version: 2
jobs:
  setup:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run: apk add make curl
      - run: mkdir -vp ~/.docker/cli-plugins/
      - run: curl --silent -L --output ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64
      - run: chmod a+x ~/.docker/cli-plugins/docker-buildx
      - run: docker run  --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
      - run: docker buildx version
      - run: docker buildx ls
      - run: docker context create testContext
      - run: docker buildx create --use testContext
      - run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

  build:
    docker:
      - image: docker:stable
    steps:
      - run: |
          docker buildx build --push \
            --progress=plain \
            --platform linux/arm64/v8,linux/amd64,linux/386,linux/arm/v7,linux/ppc64le,linux/s390x \
            --tag 2tefan/multiarch-test:buildx .

workflows:
 version: 2

 Test_Workflow:
   jobs:
     - setup
     - build:
          requires:
            - setup
